routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Staff\StaffController;
use App\Http\Controllers\Department\DepartmentController;
use App\Http\Controllers\Setka\SetkaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('staffs', StaffController::class);
Route::resource('departments', DepartmentController::class);
Route::get('setka', [SetkaController::class, 'index'])->name('setka.index');

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    use HasFactory;

    protected $table = 'staffs';

    protected $genders = [
        1=>'Мужской',
        0=>'Женский'
    ];

    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'gender',
        'salary',
    ];

    public function getGenderNameAttribute()
    {
        return $this->genders[$this->gender]??'';
    }

    public function getFullNameAttribute()
    {
        return "$this->first_name $this->last_name $this->middle_name";
    }

    public function departments()
    {
        return $this->belongsToMany(Department::class, 'staffs_departments');
    }
}

app/Http/Controllers/Staff/StaffController.php
<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use App\Http\Requests\Staff\StoreStaffRequest;
use App\Http\Requests\Staff\UpdateStaffRequest;
use App\Repositories\Department\DepartmentEloquentRepository;
use App\Repositories\Staff\StaffRepositoryContract;

class StaffController extends Controller
{
    protected $departmentRepository;
    protected $staffRepository;

    public function __construct(StaffRepositoryContract $staffRepository,
                DepartmentEloquentRepository $departmentRepository
        )
    {
        $this->staffRepository = $staffRepository;
        $this->departmentRepository = $departmentRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staffs = $this->staffRepository->paginate();
        return view('staff.index', compact( 'staffs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = $this->departmentRepository->all()->prepend('', '')->pluck('name', 'id');
        return view('staff.create', compact( 'departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreStaffRequest $request)
    {
        $this->staffRepository->create($request->validated());
        session()->flash('flash_message', trans('alerts.general.success_add'));
        return redirect()->route('staffs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $staff = $this->staffRepository->findById($id);
        return view('staff.show', compact('staff'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $staff = $this->staffRepository->findById($id);
        $departments = $this->departmentRepository->all()->prepend('', '')->pluck('name', 'id');
        return view('staff.edit', compact('staff', 'departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStaffRequest $request, $id)
    {
        $this->staffRepository->update($id, $request->validated());
        session()->flash('flash_message', trans('alerts.general.success_edit'));
        return redirect()->route('staffs.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->staffRepository->delete($id);
        session()->flash('flash_message', trans('alerts.general.success_delete'));
        return redirect()->route('staffs.index');
    }
}

resources/views/staff/create.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.create') }}</h3>
        </div>
        <div>
            @include('vendor.errors.errors')
            {!! Form::open(['route' => 'staffs.store','class'=>'form-horizontal','id'=>'form-staff']) !!}
            @include('staff.partials.fields')
            {!! Form::close() !!}
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.cancel'), ['class' => 'btn btn-default']) !!}
            {!! Form::submit(trans('actions.general.save'), ['class' => 'btn btn-primary','form'=>'form-staff']) !!}
        </div>
    </div>
@endsection

resources/views/staff/edit.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.edit') }}</h3>
        </div>
        <div>
            @include('vendor.errors.errors')
            {!! Form::model($staff , ['route' => ['staffs.update', $staff->id],
                'method' => 'patch', 'class'=>'form-horizontal','id'=>'form-staff']) !!}
            @include('staff.partials.fields')
            {!! Form::close() !!}
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.cancel'), ['class' => 'btn btn-default']) !!}
            {!! Form::submit(trans('actions.general.save'), ['class' => 'btn btn-primary','form'=>'form-staff']) !!}
        </div>
    </div>
@endsection

resources/views/staff/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="mt-5">
        @include('vendor.errors.success')
        @include('vendor.errors.error')
        <a href="{{route('staffs.create')}}" class = 'btn btn-primary'>{{trans('actions.general.create')}}</a>
        <br>
        <br>
        <table class="table">
            <thead>
            <tr class="table-primary">
                <td>ID</td>
                <td>{{trans('staff.first_name')}}</td>
                <td>{{trans('staff.last_name')}}</td>
                <td>{{trans('staff.middle_name')}}</td>
                <td>{{trans('staff.gender')}}</td>
                <td>{{trans('staff.salary')}}</td>
                <td>{{trans('staff.departments')}}</td>
                <td>{{trans('actions.general.action')}}</td>
            </tr>
            </thead>
            <tbody>
            @foreach($staffs as $staff)
                <tr>
                    <td>{{$staff->id}}</td>
                    <td>{{$staff->first_name}}</td>
                    <td>{{$staff->last_name}}</td>
                    <td>{{$staff->middle_name}}</td>
                    <td>{{$staff->genderName}}</td>
                    <td>{{$staff->salary}}</td>
                    <td>{{$staff->departments->implode('name', ', ')}}</td>
                    <td class="text-center">
                        <a href="{{ route('staffs.show', $staff->id)}}" class="btn btn-success btn-sm">{{trans('actions.general.view')}}</a>
                        <a href="{{ route('staffs.edit', $staff->id)}}" class="btn btn-success btn-sm">{{trans('actions.general.edit')}}</a>
                        <form action="{{ route('staffs.destroy', $staff->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">{{trans('actions.general.delete')}}</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    <div>
    @if(isset($staffs))
        {{$staffs->render() }}
    @endif
@endsection

resources/views/staff/show.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.view') }}</h3>
        </div>
        <div>
            @include('staff.partials.show_fields')
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.back'), ['class' => 'btn btn-default']) !!}
        </div>
    </div>
@endsection