routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Staff\StaffController;
use App\Http\Controllers\Department\DepartmentController;
use App\Http\Controllers\Setka\SetkaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('staffs', StaffController::class);
Route::resource('departments', DepartmentController::class);
Route::get('setka', [SetkaController::class, 'index'])->name('setka.index');

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $table = 'departments';

    protected $fillable = [
        'name',
    ];

    public function staffs()
    {
        return $this->belongsToMany(Staff::class, 'staffs_departments');
    }
}

app/Http/Controllers/Department/DepartmentController.php
<?php

namespace App\Http\Controllers\Department;

use App\Http\Controllers\Controller;
use App\Http\Requests\Department\StoreDepartmentRequest;
use App\Http\Requests\Department\UpdateDepartmentRequest;
use App\Repositories\Department\DepartmentRepositoryContract;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    protected $departmentRepository;

    public function __construct(DepartmentRepositoryContract $departmentRepository)
    {
        $this->departmentRepository = $departmentRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = $this->departmentRepository->paginate();
        return view('department.index', compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDepartmentRequest $request)
    {
        $this->departmentRepository->create($request->validated());
        session()->flash('flash_message', trans('alerts.general.success_add'));
        return redirect()->route('departments.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $department = $this->departmentRepository->findById($id);
        return view('department.show', compact( 'department'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = $this->departmentRepository->findById($id);
        return view('department.edit', compact( 'department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDepartmentRequest $request, $id)
    {
        $this->departmentRepository->update($id, $request->validated());
        session()->flash('flash_message', trans('alerts.general.success_edit'));
        return redirect()->route('departments.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->departmentRepository->delete($id)){
            session()->flash('flash_message', trans('alerts.general.success_delete'));
        } else {
            session()->flash('flash_message_error', trans('alerts.general.access_denied'));
        }
        return redirect()->route('departments.index');
    }
}

resources/views/department/create.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.create') }}</h3>
        </div>
        <div>
            @include('vendor.errors.errors')
            {!! Form::open(['route' => 'departments.store','class'=>'form-horizontal','id'=>'form-department']) !!}
                @include('department.partials.fields')
            {!! Form::close() !!}
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.cancel'), ['class' => 'btn btn-default']) !!}
            {!! Form::submit(trans('actions.general.save'), ['class' => 'btn btn-primary','form'=>'form-department']) !!}
        </div>
    </div>
@endsection

resources/views/department/edit.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.edit') }}</h3>
        </div>
        <div>
            @include('vendor.errors.errors')
            {!! Form::model($department , ['route' => ['departments.update', $department->id],
                'method' => 'patch', 'class'=>'form-horizontal','id'=>'form-department']) !!}
            @include('department.partials.fields')
            {!! Form::close() !!}
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.cancel'), ['class' => 'btn btn-default']) !!}
            {!! Form::submit(trans('actions.general.save'), ['class' => 'btn btn-primary','form'=>'form-department']) !!}
        </div>
    </div>
@endsection

resources/views/department/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="mt-5">
        @include('vendor.errors.success')
        @include('vendor.errors.error')
        <a href="{{route('departments.create')}}" class = 'btn btn-primary'>{{trans('actions.general.create')}}</a>
        <br>
        <br>
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <td>ID</td>
                    <td>{{trans('department.name')}}</td>
                    <td>{{trans('department.count_staff')}}</td>
                    <td>{{trans('department.max_salary')}}</td>
                    <td>{{trans('actions.general.action')}}</td>
                </tr>
            </thead>
            <tbody>
                @foreach($departments as $department)
                    <tr>
                        <td>{{$department->id}}</td>
                        <td>{{$department->name}}</td>
                        <td>{{$department->staffs->count()}}</td>
                        <td>{{$department->staffs->max('salary')}}</td>
                        <td class="text-center">
                            <a href="{{ route('departments.show', $department->id)}}" class="btn btn-success btn-sm">{{trans('actions.general.view')}}</a>
                            <a href="{{ route('departments.edit', $department->id)}}" class="btn btn-success btn-sm">{{trans('actions.general.edit')}}</a>
                            <form action="{{ route('departments.destroy', $department->id)}}" method="post" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit">{{trans('actions.general.delete')}}</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    <div>
    @if(isset($departments))
        {{$departments->render() }}
    @endif
@endsection

resources/views/department/show.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <h3>{{ trans('actions.general.view') }}</h3>
        </div>
        <div>
            @include('department.partials.show_fields')
        </div>
        <div>
            {!!  link_to(URL::previous(), trans('actions.general.back'), ['class' => 'btn btn-default']) !!}
        </div>
    </div>
@endsection